### PR TITLE
Fix broken DI on preview asset

### PR DESCRIPTION
**Pull request by Mosnar**
The PreviewAsset's namespace needs to match its folder structure in order for composer's dependency injection to properly locate it.

Fixes this error on Entry edit page:
```
ReflectionException: Class vaersaagod\seomate\assets\PreviewAsset does not exist in /var/app/current/vendor/yiisoft/yii2/di/Container.php:431
Stack trace:
#0 /var/app/current/vendor/yiisoft/yii2/di/Container.php(431): ReflectionClass->__construct('vaersaagod\\seom...')
#1 /var/app/current/vendor/yiisoft/yii2/di/Container.php(365): yii\di\Container->getDependencies('vaersaagod\\seom...')
#2 /var/app/current/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('vaersaagod\\seom...', Array, Array)
#3 /var/app/current/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('vaersaagod\\seom...', Array, Array)
#4 /var/app/current/vendor/yiisoft/yii2/web/AssetManager.php(264): yii\BaseYii::createObject(Array)
#5 /var/app/current/vendor/yiisoft/yii2/web/AssetManager.php(237): yii\web\AssetManager->loadBundle('vaersaagod\\seom...', Array, true)
#6 /var/app/current/vendor/yiisoft/yii2/web/View.php(286): yii\web\AssetManager->getBundle('vaersaagod\\seom...')
#7 /var/app/current/vendor/vaersaagod/seomate/src/SEOMate.php(243): yii\web\View->registerAssetBundle('vaersaagod\\seom...')
#8 /var/app/current/vendor/craftcms/cms/src/web/View.php(1275): vaersaagod\seomate\SEOMate->registerPreviewAssetsBundle(Array)
#9 /var/app/current/storage/runtime/compiled_templates/91/918557303d08ad4ce8a57a6607f26b25e354944049fb09173cf0201bb504fd7a.php(61): craft\web\View->invokeHook('cp.entries.edit', Array)
#10 /var/app/current/vendor/twig/twig/src/Template.php(382): __TwigTemplate_5de08d87835ef6aef2389ff7ab817bcf933ef79efe077b63123b1f9fa0c08966->doDisplay(Array, Array)
#11 /var/app/current/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /var/app/current/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#13 /var/app/current/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#14 /var/app/current/vendor/twig/twig/src/Template.php(367): craft\web\twig\Template->display(Array)
#15 /var/app/current/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#16 /var/app/current/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#17 /var/app/current/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('entries/_edit', Array)
#18 /var/app/current/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('entries/_edit', Array)
#19 /var/app/current/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('entries/_edit', Array)
#20 /var/app/current/vendor/craftcms/cms/src/controllers/EntriesController.php(383): craft\web\Controller->renderTemplate('entries/_edit', Array)
#21 [internal function]: craft\controllers\EntriesController->actionEditEntry('homepage', 2, NULL, NULL, NULL, Object(craft\elements\Entry))
#22 /var/app/current/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 /var/app/current/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 /var/app/current/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit-entry', Array)
#25 /var/app/current/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#26 /var/app/current/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('entries/edit-en...', Array)
#27 /var/app/current/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#28 /var/app/current/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#29 /var/app/current/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 /var/app/current/web/index.php(21): yii\base\Application->run()
#31 {main}

Next yii\base\InvalidConfigException: Failed to instantiate component or class "vaersaagod\seomate\assets\PreviewAsset". in /var/app/current/vendor/yiisoft/yii2/di/Container.php:433
Stack trace:
#0 /var/app/current/vendor/yiisoft/yii2/di/Container.php(365): yii\di\Container->getDependencies('vaersaagod\\seom...')
#1 /var/app/current/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('vaersaagod\\seom...', Array, Array)
#2 /var/app/current/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('vaersaagod\\seom...', Array, Array)
#3 /var/app/current/vendor/yiisoft/yii2/web/AssetManager.php(264): yii\BaseYii::createObject(Array)
#4 /var/app/current/vendor/yiisoft/yii2/web/AssetManager.php(237): yii\web\AssetManager->loadBundle('vaersaagod\\seom...', Array, true)
#5 /var/app/current/vendor/yiisoft/yii2/web/View.php(286): yii\web\AssetManager->getBundle('vaersaagod\\seom...')
#6 /var/app/current/vendor/vaersaagod/seomate/src/SEOMate.php(243): yii\web\View->registerAssetBundle('vaersaagod\\seom...')
#7 /var/app/current/vendor/craftcms/cms/src/web/View.php(1275): vaersaagod\seomate\SEOMate->registerPreviewAssetsBundle(Array)
#8 /var/app/current/storage/runtime/compiled_templates/91/918557303d08ad4ce8a57a6607f26b25e354944049fb09173cf0201bb504fd7a.php(61): craft\web\View->invokeHook('cp.entries.edit', Array)
#9 /var/app/current/vendor/twig/twig/src/Template.php(382): __TwigTemplate_5de08d87835ef6aef2389ff7ab817bcf933ef79efe077b63123b1f9fa0c08966->doDisplay(Array, Array)
#10 /var/app/current/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /var/app/current/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /var/app/current/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#13 /var/app/current/vendor/twig/twig/src/Template.php(367): craft\web\twig\Template->display(Array)
#14 /var/app/current/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#15 /var/app/current/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#16 /var/app/current/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('entries/_edit', Array)
#17 /var/app/current/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('entries/_edit', Array)
#18 /var/app/current/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('entries/_edit', Array)
#19 /var/app/current/vendor/craftcms/cms/src/controllers/EntriesController.php(383): craft\web\Controller->renderTemplate('entries/_edit', Array)
#20 [internal function]: craft\controllers\EntriesController->actionEditEntry('homepage', 2, NULL, NULL, NULL, Object(craft\elements\Entry))
#21 /var/app/current/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /var/app/current/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#23 /var/app/current/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit-entry', Array)
#24 /var/app/current/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#25 /var/app/current/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('entries/edit-en...', Array)
#26 /var/app/current/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#27 /var/app/current/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#28 /var/app/current/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /var/app/current/web/index.php(21): yii\base\Application->run()
#30 {main}
```

### CODE REVIEW

**Comment by aelvan** [comment]
Thanks for contributing.

I still don't understand why we don't get an error on that. But according to PSR-0, it should have the full namespace as you've changed it to... When were you getting the error? Upon install, or after? What environment are you on?

**Comment by Mosnar** [comment]
@aelvan Thanks for getting back to me. I agree, it's odd that I'm the only one getting this error. I observed this particular issue in two environments: my local development environment, running this PHP 7.2 Docker Image: https://github.com/venveo/docker-baseimage/blob/master/alpine/php7-apache/Dockerfile

As well as in our production/staging environments running Elastic Beanstalk (`PHP 7.2 running on 64bit Amazon Linux/2.8.9`).

**Comment by aelvan** [comment]
@Mosnar How did you install the plugin?

**Comment by Mosnar** [comment]
I ran `composer require vaersaagod/seomate` which resulted in the following changes:

composer.json:
```
        "vaersaagod/seomate": "^1.0"
```

composer.lock
```

        {
            "name": "vaersaagod/seomate",
            "version": "1.0.1",
            "source": {
                "type": "git",
                "url": "https://github.com/vaersaagod/seomate.git",
                "reference": "5e040097530437b5aac3e4c879143426d716c2fd"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/vaersaagod/seomate/zipball/5e040097530437b5aac3e4c879143426d716c2fd",
                "reference": "5e040097530437b5aac3e4c879143426d716c2fd",
                "shasum": ""
            },
            "require": {
                "craftcms/cms": "^3.0.0",
                "spatie/schema-org": "^2.0"
            },
            "type": "craft-plugin",
            "extra": {
                "name": "SEOMate",
                "handle": "seomate",
                "hasCpSettings": false,
                "hasCpSection": false,
                "changelogUrl": "https://raw.githubusercontent.com/vaersaagod/seomate/master/CHANGELOG.md",
                "components": [],
                "class": "vaersaagod\\seomate\\SEOMate"
            },
            "autoload": {
                "psr-4": {
                    "vaersaagod\\seomate\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Værsågod",
                    "homepage": "https://www.vaersaagod.no/"
                }
            ],
            "description": "SEO, mate! It's important.",
            "keywords": [
                "Craft",
                "JSON-LD",
                "cms",
                "craft-plugin",
                "craftcms",
                "meta",
                "seo",
                "seomate"
            ],
            "time": "2019-04-30T12:31:02+00:00"
        },
```

The error only occurs when the asset bundle is attempted to be loaded (edit entry screen)

**Comment by aelvan** [comment]
Huh, so weird. Maybe it has something to do with the composer version and/or configuration.

Anyways, the namespace was wrong, I just don't get why we're not getting the same error. Anyways, thanks again for reporting, hope you enjoy the plugin.

**Pull request merged**
